"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Adeptrix6.py']
DATA_FILES = []
OPTIONS = {'packages': ['tkinter', 'tkinterdnd2']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
